# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step to check out the repository contents
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step to configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v2

      # Upload the artifact for deployment
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Adjust the path if your static files are in a subdirectory (e.g., './public' or './dist')

      # Step to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
